'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34014
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.34014.
'
Namespace WSGuateFAC
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="GuatefacBinding", [Namespace]:="http://dbguatefac/Guatefac.wsdl")>  _
    Partial Public Class Guatefac
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private anulaDocumentoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private generaDocumentoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.FACE.My.MySettings.Default.FACE_WSGuateFAC_Guatefac
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event anulaDocumentoCompleted As anulaDocumentoCompletedEventHandler
        
        '''<remarks/>
        Public Event generaDocumentoCompleted As generaDocumentoCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace:="Guatefac", ResponseNamespace:="Guatefac")>  _
        Public Function anulaDocumento(ByVal pUsuario As String, ByVal pPassword As String, ByVal pNitEmisor As String, ByVal pSerie As String, ByVal pPreimpreso As String, ByVal pNitComprador As String, ByVal pFechaAnulacion As String, ByVal pMotivoAnulacion As String) As <System.Xml.Serialization.SoapElementAttribute("return")> String
            Dim results() As Object = Me.Invoke("anulaDocumento", New Object() {pUsuario, pPassword, pNitEmisor, pSerie, pPreimpreso, pNitComprador, pFechaAnulacion, pMotivoAnulacion})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub anulaDocumentoAsync(ByVal pUsuario As String, ByVal pPassword As String, ByVal pNitEmisor As String, ByVal pSerie As String, ByVal pPreimpreso As String, ByVal pNitComprador As String, ByVal pFechaAnulacion As String, ByVal pMotivoAnulacion As String)
            Me.anulaDocumentoAsync(pUsuario, pPassword, pNitEmisor, pSerie, pPreimpreso, pNitComprador, pFechaAnulacion, pMotivoAnulacion, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub anulaDocumentoAsync(ByVal pUsuario As String, ByVal pPassword As String, ByVal pNitEmisor As String, ByVal pSerie As String, ByVal pPreimpreso As String, ByVal pNitComprador As String, ByVal pFechaAnulacion As String, ByVal pMotivoAnulacion As String, ByVal userState As Object)
            If (Me.anulaDocumentoOperationCompleted Is Nothing) Then
                Me.anulaDocumentoOperationCompleted = AddressOf Me.OnanulaDocumentoOperationCompleted
            End If
            Me.InvokeAsync("anulaDocumento", New Object() {pUsuario, pPassword, pNitEmisor, pSerie, pPreimpreso, pNitComprador, pFechaAnulacion, pMotivoAnulacion}, Me.anulaDocumentoOperationCompleted, userState)
        End Sub
        
        Private Sub OnanulaDocumentoOperationCompleted(ByVal arg As Object)
            If (Not (Me.anulaDocumentoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent anulaDocumentoCompleted(Me, New anulaDocumentoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace:="Guatefac", ResponseNamespace:="Guatefac")>  _
        Public Function generaDocumento(ByVal pUsuario As String, ByVal pPassword As String, ByVal pNitEmisor As String, ByVal pEstablecimiento As Decimal, ByVal pTipoDoc As Decimal, ByVal pIdMaquina As String, ByVal pTipoRespuesta As String, ByVal pXml As String) As <System.Xml.Serialization.SoapElementAttribute("return")> String
            Dim results() As Object = Me.Invoke("generaDocumento", New Object() {pUsuario, pPassword, pNitEmisor, pEstablecimiento, pTipoDoc, pIdMaquina, pTipoRespuesta, pXml})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub generaDocumentoAsync(ByVal pUsuario As String, ByVal pPassword As String, ByVal pNitEmisor As String, ByVal pEstablecimiento As Decimal, ByVal pTipoDoc As Decimal, ByVal pIdMaquina As String, ByVal pTipoRespuesta As String, ByVal pXml As String)
            Me.generaDocumentoAsync(pUsuario, pPassword, pNitEmisor, pEstablecimiento, pTipoDoc, pIdMaquina, pTipoRespuesta, pXml, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub generaDocumentoAsync(ByVal pUsuario As String, ByVal pPassword As String, ByVal pNitEmisor As String, ByVal pEstablecimiento As Decimal, ByVal pTipoDoc As Decimal, ByVal pIdMaquina As String, ByVal pTipoRespuesta As String, ByVal pXml As String, ByVal userState As Object)
            If (Me.generaDocumentoOperationCompleted Is Nothing) Then
                Me.generaDocumentoOperationCompleted = AddressOf Me.OngeneraDocumentoOperationCompleted
            End If
            Me.InvokeAsync("generaDocumento", New Object() {pUsuario, pPassword, pNitEmisor, pEstablecimiento, pTipoDoc, pIdMaquina, pTipoRespuesta, pXml}, Me.generaDocumentoOperationCompleted, userState)
        End Sub
        
        Private Sub OngeneraDocumentoOperationCompleted(ByVal arg As Object)
            If (Not (Me.generaDocumentoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent generaDocumentoCompleted(Me, New generaDocumentoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")>  _
    Public Delegate Sub anulaDocumentoCompletedEventHandler(ByVal sender As Object, ByVal e As anulaDocumentoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class anulaDocumentoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")>  _
    Public Delegate Sub generaDocumentoCompletedEventHandler(ByVal sender As Object, ByVal e As generaDocumentoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class generaDocumentoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
End Namespace
