CREATE FUNCTION CORRIGEDOC_NUM(IN VAL NVARCHAR(20)) 
RETURNS a NVARCHAR(20)
LANGUAGE SQLSCRIPT READS SQL DATA 
AS 
POSINI INT;
BEGIN 

 POSINI:=LOCATE('0',:VAL);
 a :=SUBSTRING(:VAL,:POSINI + 1,LENGTH(:VAL));
--    SELECT sso_obtieneserieCV('1010101') from dummy
END;