CREATE FUNCTION [dbo].[CORRIGEDOC_NUM](@DOCNUM VARCHAR(20)) RETURNS VARCHAR(20)
AS 
BEGin
 
 DECLARE @POSINI INT
 DECLARE @RESULT VARCHAR(20)
 
 SET @POSINI=CHARINDEX('0',@DOCNUM)
 SET @RESULT=SUBSTRING(@DOCNUM,@POSINI+1,LEN(@DOCNUM))
 
 RETURN @RESULT
 
END
