'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34014
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.34014.
'
Namespace InfileWS
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="ingfacePortBinding", [Namespace]:="http://listener.ingface.com/"),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(resultado))>  _
    Partial Public Class ingface
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private helloOperationCompleted As System.Threading.SendOrPostCallback
        
        Private registrarDteOperationCompleted As System.Threading.SendOrPostCallback
        
        Private anulacionDteOperationCompleted As System.Threading.SendOrPostCallback
        
        Private cierreOperationCompleted As System.Threading.SendOrPostCallback
        
        Private validacionDteOperationCompleted As System.Threading.SendOrPostCallback
        
        Private cargarDteOperationCompleted As System.Threading.SendOrPostCallback
        
        Private registrarDteSapOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.FACE.My.MySettings.Default.FACE_InfileWS_ingface
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event helloCompleted As helloCompletedEventHandler
        
        '''<remarks/>
        Public Event registrarDteCompleted As registrarDteCompletedEventHandler
        
        '''<remarks/>
        Public Event anulacionDteCompleted As anulacionDteCompletedEventHandler
        
        '''<remarks/>
        Public Event cierreCompleted As cierreCompletedEventHandler
        
        '''<remarks/>
        Public Event validacionDteCompleted As validacionDteCompletedEventHandler
        
        '''<remarks/>
        Public Event cargarDteCompleted As cargarDteCompletedEventHandler
        
        '''<remarks/>
        Public Event registrarDteSapCompleted As registrarDteSapCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="http://listener.ingface.com/", ResponseNamespace:="http://listener.ingface.com/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function hello(<System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal name As String) As <System.Xml.Serialization.XmlElementAttribute("return", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> String
            Dim results() As Object = Me.Invoke("hello", New Object() {name})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub helloAsync(ByVal name As String)
            Me.helloAsync(name, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub helloAsync(ByVal name As String, ByVal userState As Object)
            If (Me.helloOperationCompleted Is Nothing) Then
                Me.helloOperationCompleted = AddressOf Me.OnhelloOperationCompleted
            End If
            Me.InvokeAsync("hello", New Object() {name}, Me.helloOperationCompleted, userState)
        End Sub
        
        Private Sub OnhelloOperationCompleted(ByVal arg As Object)
            If (Not (Me.helloCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent helloCompleted(Me, New helloCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="http://listener.ingface.com/", ResponseNamespace:="http://listener.ingface.com/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function registrarDte(<System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal dte As requestDte) As <System.Xml.Serialization.XmlElementAttribute("return", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> responseDte
            Dim results() As Object = Me.Invoke("registrarDte", New Object() {dte})
            Return CType(results(0),responseDte)
        End Function
        
        '''<remarks/>
        Public Overloads Sub registrarDteAsync(ByVal dte As requestDte)
            Me.registrarDteAsync(dte, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub registrarDteAsync(ByVal dte As requestDte, ByVal userState As Object)
            If (Me.registrarDteOperationCompleted Is Nothing) Then
                Me.registrarDteOperationCompleted = AddressOf Me.OnregistrarDteOperationCompleted
            End If
            Me.InvokeAsync("registrarDte", New Object() {dte}, Me.registrarDteOperationCompleted, userState)
        End Sub
        
        Private Sub OnregistrarDteOperationCompleted(ByVal arg As Object)
            If (Not (Me.registrarDteCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent registrarDteCompleted(Me, New registrarDteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="http://listener.ingface.com/", ResponseNamespace:="http://listener.ingface.com/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function anulacionDte(<System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal dte As requestAnulacionDte) As <System.Xml.Serialization.XmlElementAttribute("return", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> responseAnulacionDte
            Dim results() As Object = Me.Invoke("anulacionDte", New Object() {dte})
            Return CType(results(0),responseAnulacionDte)
        End Function
        
        '''<remarks/>
        Public Overloads Sub anulacionDteAsync(ByVal dte As requestAnulacionDte)
            Me.anulacionDteAsync(dte, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub anulacionDteAsync(ByVal dte As requestAnulacionDte, ByVal userState As Object)
            If (Me.anulacionDteOperationCompleted Is Nothing) Then
                Me.anulacionDteOperationCompleted = AddressOf Me.OnanulacionDteOperationCompleted
            End If
            Me.InvokeAsync("anulacionDte", New Object() {dte}, Me.anulacionDteOperationCompleted, userState)
        End Sub
        
        Private Sub OnanulacionDteOperationCompleted(ByVal arg As Object)
            If (Not (Me.anulacionDteCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent anulacionDteCompleted(Me, New anulacionDteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="http://listener.ingface.com/", ResponseNamespace:="http://listener.ingface.com/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function cierre(<System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal usuario As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal clave As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal codigoEstablecimiento As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal mes As Integer, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal anio As Integer) As <System.Xml.Serialization.XmlElementAttribute("return", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> responseCierre
            Dim results() As Object = Me.Invoke("cierre", New Object() {usuario, clave, codigoEstablecimiento, mes, anio})
            Return CType(results(0),responseCierre)
        End Function
        
        '''<remarks/>
        Public Overloads Sub cierreAsync(ByVal usuario As String, ByVal clave As String, ByVal codigoEstablecimiento As String, ByVal mes As Integer, ByVal anio As Integer)
            Me.cierreAsync(usuario, clave, codigoEstablecimiento, mes, anio, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub cierreAsync(ByVal usuario As String, ByVal clave As String, ByVal codigoEstablecimiento As String, ByVal mes As Integer, ByVal anio As Integer, ByVal userState As Object)
            If (Me.cierreOperationCompleted Is Nothing) Then
                Me.cierreOperationCompleted = AddressOf Me.OncierreOperationCompleted
            End If
            Me.InvokeAsync("cierre", New Object() {usuario, clave, codigoEstablecimiento, mes, anio}, Me.cierreOperationCompleted, userState)
        End Sub
        
        Private Sub OncierreOperationCompleted(ByVal arg As Object)
            If (Not (Me.cierreCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent cierreCompleted(Me, New cierreCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="http://listener.ingface.com/", ResponseNamespace:="http://listener.ingface.com/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function validacionDte(<System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal validacion As requestValidacion) As <System.Xml.Serialization.XmlElementAttribute("return", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> responseValidacion
            Dim results() As Object = Me.Invoke("validacionDte", New Object() {validacion})
            Return CType(results(0),responseValidacion)
        End Function
        
        '''<remarks/>
        Public Overloads Sub validacionDteAsync(ByVal validacion As requestValidacion)
            Me.validacionDteAsync(validacion, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub validacionDteAsync(ByVal validacion As requestValidacion, ByVal userState As Object)
            If (Me.validacionDteOperationCompleted Is Nothing) Then
                Me.validacionDteOperationCompleted = AddressOf Me.OnvalidacionDteOperationCompleted
            End If
            Me.InvokeAsync("validacionDte", New Object() {validacion}, Me.validacionDteOperationCompleted, userState)
        End Sub
        
        Private Sub OnvalidacionDteOperationCompleted(ByVal arg As Object)
            If (Not (Me.validacionDteCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent validacionDteCompleted(Me, New validacionDteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="http://listener.ingface.com/", ResponseNamespace:="http://listener.ingface.com/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function cargarDte(<System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal dte As requestDte, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal anexo As String) As <System.Xml.Serialization.XmlElementAttribute("return", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> responseDte
            Dim results() As Object = Me.Invoke("cargarDte", New Object() {dte, anexo})
            Return CType(results(0),responseDte)
        End Function
        
        '''<remarks/>
        Public Overloads Sub cargarDteAsync(ByVal dte As requestDte, ByVal anexo As String)
            Me.cargarDteAsync(dte, anexo, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub cargarDteAsync(ByVal dte As requestDte, ByVal anexo As String, ByVal userState As Object)
            If (Me.cargarDteOperationCompleted Is Nothing) Then
                Me.cargarDteOperationCompleted = AddressOf Me.OncargarDteOperationCompleted
            End If
            Me.InvokeAsync("cargarDte", New Object() {dte, anexo}, Me.cargarDteOperationCompleted, userState)
        End Sub
        
        Private Sub OncargarDteOperationCompleted(ByVal arg As Object)
            If (Not (Me.cargarDteCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent cargarDteCompleted(Me, New cargarDteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="http://listener.ingface.com/", ResponseNamespace:="http://listener.ingface.com/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function registrarDteSap(<System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal dte As requestDte) As <System.Xml.Serialization.XmlElementAttribute("return", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> responseDteSap
            Dim results() As Object = Me.Invoke("registrarDteSap", New Object() {dte})
            Return CType(results(0),responseDteSap)
        End Function
        
        '''<remarks/>
        Public Overloads Sub registrarDteSapAsync(ByVal dte As requestDte)
            Me.registrarDteSapAsync(dte, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub registrarDteSapAsync(ByVal dte As requestDte, ByVal userState As Object)
            If (Me.registrarDteSapOperationCompleted Is Nothing) Then
                Me.registrarDteSapOperationCompleted = AddressOf Me.OnregistrarDteSapOperationCompleted
            End If
            Me.InvokeAsync("registrarDteSap", New Object() {dte}, Me.registrarDteSapOperationCompleted, userState)
        End Sub
        
        Private Sub OnregistrarDteSapOperationCompleted(ByVal arg As Object)
            If (Not (Me.registrarDteSapCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent registrarDteSapCompleted(Me, New registrarDteSapCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://listener.ingface.com/")>  _
    Partial Public Class requestDte
        
        Private claveField As String
        
        Private dteField As dte
        
        Private usuarioField As String
        
        Private validadorField As Boolean
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property clave() As String
            Get
                Return Me.claveField
            End Get
            Set
                Me.claveField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property dte() As dte
            Get
                Return Me.dteField
            End Get
            Set
                Me.dteField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property usuario() As String
            Get
                Return Me.usuarioField
            End Get
            Set
                Me.usuarioField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property validador() As Boolean
            Get
                Return Me.validadorField
            End Get
            Set
                Me.validadorField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://listener.ingface.com/")>  _
    Partial Public Class dte
        
        Private caeField As String
        
        Private codigoEstablecimientoField As String
        
        Private codigoMonedaField As String
        
        Private correoCompradorField As String
        
        Private departamentoCompradorField As String
        
        Private departamentoVendedorField As String
        
        Private descripcionOtroImpuestoField As String
        
        Private detalleDteField() As detalleDte
        
        Private detalleImpuestosIvaField As Double
        
        Private detalleImpuestosIvaFieldSpecified As Boolean
        
        Private direccionComercialCompradorField As String
        
        Private direccionComercialVendedorField As String
        
        Private estadoDocumentoField As String
        
        Private fechaAnulacionField As Date
        
        Private fechaAnulacionFieldSpecified As Boolean
        
        Private fechaDocumentoField As Date
        
        Private fechaDocumentoFieldSpecified As Boolean
        
        Private fechaResolucionField As Date
        
        Private fechaResolucionFieldSpecified As Boolean
        
        Private idDispositivoField As String
        
        Private importeBrutoField As Double
        
        Private importeBrutoFieldSpecified As Boolean
        
        Private importeDescuentoField As Double
        
        Private importeDescuentoFieldSpecified As Boolean
        
        Private importeNetoGravadoField As Double
        
        Private importeNetoGravadoFieldSpecified As Boolean
        
        Private importeOtrosImpuestosField As Double
        
        Private importeOtrosImpuestosFieldSpecified As Boolean
        
        Private importeTotalExentoField As Double
        
        Private importeTotalExentoFieldSpecified As Boolean
        
        Private montoTotalOperacionField As Double
        
        Private municipioCompradorField As String
        
        Private municipioVendedorField As String
        
        Private nitCompradorField As String
        
        Private nitGFACEField As String
        
        Private nitVendedorField As String
        
        Private nombreComercialCompradorField As String
        
        Private nombreComercialRazonSocialVendedorField As String
        
        Private nombreCompletoVendedorField As String
        
        Private numeroDocumentoField As String
        
        Private numeroDteField As String
        
        Private numeroResolucionField As String
        
        Private observacionesField As String
        
        Private personalizado_01Field As String
        
        Private personalizado_02Field As String
        
        Private personalizado_03Field As String
        
        Private personalizado_04Field As String
        
        Private personalizado_05Field As String
        
        Private personalizado_06Field As String
        
        Private personalizado_07Field As String
        
        Private personalizado_08Field As String
        
        Private personalizado_09Field As String
        
        Private personalizado_10Field As String
        
        Private personalizado_11Field As String
        
        Private personalizado_12Field As String
        
        Private personalizado_13Field As String
        
        Private personalizado_14Field As String
        
        Private personalizado_15Field As String
        
        Private personalizado_16Field As String
        
        Private personalizado_17Field As String
        
        Private personalizado_18Field As String
        
        Private personalizado_19Field As String
        
        Private personalizado_20Field As String
        
        Private rangoFinalAutorizadoField As String
        
        Private rangoInicialAutorizadoField As String
        
        Private regimen2989Field As Boolean
        
        Private regimenISRField As String
        
        Private serieAutorizadaField As String
        
        Private serieDocumentoField As String
        
        Private telefonoCompradorField As String
        
        Private tipoCambioField As Double
        
        Private tipoCambioFieldSpecified As Boolean
        
        Private tipoDocumentoField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property cae() As String
            Get
                Return Me.caeField
            End Get
            Set
                Me.caeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property codigoEstablecimiento() As String
            Get
                Return Me.codigoEstablecimientoField
            End Get
            Set
                Me.codigoEstablecimientoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property codigoMoneda() As String
            Get
                Return Me.codigoMonedaField
            End Get
            Set
                Me.codigoMonedaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property correoComprador() As String
            Get
                Return Me.correoCompradorField
            End Get
            Set
                Me.correoCompradorField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property departamentoComprador() As String
            Get
                Return Me.departamentoCompradorField
            End Get
            Set
                Me.departamentoCompradorField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property departamentoVendedor() As String
            Get
                Return Me.departamentoVendedorField
            End Get
            Set
                Me.departamentoVendedorField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property descripcionOtroImpuesto() As String
            Get
                Return Me.descripcionOtroImpuestoField
            End Get
            Set
                Me.descripcionOtroImpuestoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("detalleDte", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true)>  _
        Public Property detalleDte() As detalleDte()
            Get
                Return Me.detalleDteField
            End Get
            Set
                Me.detalleDteField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property detalleImpuestosIva() As Double
            Get
                Return Me.detalleImpuestosIvaField
            End Get
            Set
                Me.detalleImpuestosIvaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property detalleImpuestosIvaSpecified() As Boolean
            Get
                Return Me.detalleImpuestosIvaFieldSpecified
            End Get
            Set
                Me.detalleImpuestosIvaFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property direccionComercialComprador() As String
            Get
                Return Me.direccionComercialCompradorField
            End Get
            Set
                Me.direccionComercialCompradorField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property direccionComercialVendedor() As String
            Get
                Return Me.direccionComercialVendedorField
            End Get
            Set
                Me.direccionComercialVendedorField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property estadoDocumento() As String
            Get
                Return Me.estadoDocumentoField
            End Get
            Set
                Me.estadoDocumentoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property fechaAnulacion() As Date
            Get
                Return Me.fechaAnulacionField
            End Get
            Set
                Me.fechaAnulacionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property fechaAnulacionSpecified() As Boolean
            Get
                Return Me.fechaAnulacionFieldSpecified
            End Get
            Set
                Me.fechaAnulacionFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property fechaDocumento() As Date
            Get
                Return Me.fechaDocumentoField
            End Get
            Set
                Me.fechaDocumentoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property fechaDocumentoSpecified() As Boolean
            Get
                Return Me.fechaDocumentoFieldSpecified
            End Get
            Set
                Me.fechaDocumentoFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property fechaResolucion() As Date
            Get
                Return Me.fechaResolucionField
            End Get
            Set
                Me.fechaResolucionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property fechaResolucionSpecified() As Boolean
            Get
                Return Me.fechaResolucionFieldSpecified
            End Get
            Set
                Me.fechaResolucionFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property idDispositivo() As String
            Get
                Return Me.idDispositivoField
            End Get
            Set
                Me.idDispositivoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property importeBruto() As Double
            Get
                Return Me.importeBrutoField
            End Get
            Set
                Me.importeBrutoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property importeBrutoSpecified() As Boolean
            Get
                Return Me.importeBrutoFieldSpecified
            End Get
            Set
                Me.importeBrutoFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property importeDescuento() As Double
            Get
                Return Me.importeDescuentoField
            End Get
            Set
                Me.importeDescuentoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property importeDescuentoSpecified() As Boolean
            Get
                Return Me.importeDescuentoFieldSpecified
            End Get
            Set
                Me.importeDescuentoFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property importeNetoGravado() As Double
            Get
                Return Me.importeNetoGravadoField
            End Get
            Set
                Me.importeNetoGravadoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property importeNetoGravadoSpecified() As Boolean
            Get
                Return Me.importeNetoGravadoFieldSpecified
            End Get
            Set
                Me.importeNetoGravadoFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property importeOtrosImpuestos() As Double
            Get
                Return Me.importeOtrosImpuestosField
            End Get
            Set
                Me.importeOtrosImpuestosField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property importeOtrosImpuestosSpecified() As Boolean
            Get
                Return Me.importeOtrosImpuestosFieldSpecified
            End Get
            Set
                Me.importeOtrosImpuestosFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property importeTotalExento() As Double
            Get
                Return Me.importeTotalExentoField
            End Get
            Set
                Me.importeTotalExentoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property importeTotalExentoSpecified() As Boolean
            Get
                Return Me.importeTotalExentoFieldSpecified
            End Get
            Set
                Me.importeTotalExentoFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property montoTotalOperacion() As Double
            Get
                Return Me.montoTotalOperacionField
            End Get
            Set
                Me.montoTotalOperacionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property municipioComprador() As String
            Get
                Return Me.municipioCompradorField
            End Get
            Set
                Me.municipioCompradorField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property municipioVendedor() As String
            Get
                Return Me.municipioVendedorField
            End Get
            Set
                Me.municipioVendedorField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property nitComprador() As String
            Get
                Return Me.nitCompradorField
            End Get
            Set
                Me.nitCompradorField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property nitGFACE() As String
            Get
                Return Me.nitGFACEField
            End Get
            Set
                Me.nitGFACEField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property nitVendedor() As String
            Get
                Return Me.nitVendedorField
            End Get
            Set
                Me.nitVendedorField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property nombreComercialComprador() As String
            Get
                Return Me.nombreComercialCompradorField
            End Get
            Set
                Me.nombreComercialCompradorField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property nombreComercialRazonSocialVendedor() As String
            Get
                Return Me.nombreComercialRazonSocialVendedorField
            End Get
            Set
                Me.nombreComercialRazonSocialVendedorField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property nombreCompletoVendedor() As String
            Get
                Return Me.nombreCompletoVendedorField
            End Get
            Set
                Me.nombreCompletoVendedorField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property numeroDocumento() As String
            Get
                Return Me.numeroDocumentoField
            End Get
            Set
                Me.numeroDocumentoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property numeroDte() As String
            Get
                Return Me.numeroDteField
            End Get
            Set
                Me.numeroDteField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property numeroResolucion() As String
            Get
                Return Me.numeroResolucionField
            End Get
            Set
                Me.numeroResolucionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property observaciones() As String
            Get
                Return Me.observacionesField
            End Get
            Set
                Me.observacionesField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property personalizado_01() As String
            Get
                Return Me.personalizado_01Field
            End Get
            Set
                Me.personalizado_01Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property personalizado_02() As String
            Get
                Return Me.personalizado_02Field
            End Get
            Set
                Me.personalizado_02Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property personalizado_03() As String
            Get
                Return Me.personalizado_03Field
            End Get
            Set
                Me.personalizado_03Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property personalizado_04() As String
            Get
                Return Me.personalizado_04Field
            End Get
            Set
                Me.personalizado_04Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property personalizado_05() As String
            Get
                Return Me.personalizado_05Field
            End Get
            Set
                Me.personalizado_05Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property personalizado_06() As String
            Get
                Return Me.personalizado_06Field
            End Get
            Set
                Me.personalizado_06Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property personalizado_07() As String
            Get
                Return Me.personalizado_07Field
            End Get
            Set
                Me.personalizado_07Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property personalizado_08() As String
            Get
                Return Me.personalizado_08Field
            End Get
            Set
                Me.personalizado_08Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property personalizado_09() As String
            Get
                Return Me.personalizado_09Field
            End Get
            Set
                Me.personalizado_09Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property personalizado_10() As String
            Get
                Return Me.personalizado_10Field
            End Get
            Set
                Me.personalizado_10Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property personalizado_11() As String
            Get
                Return Me.personalizado_11Field
            End Get
            Set
                Me.personalizado_11Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property personalizado_12() As String
            Get
                Return Me.personalizado_12Field
            End Get
            Set
                Me.personalizado_12Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property personalizado_13() As String
            Get
                Return Me.personalizado_13Field
            End Get
            Set
                Me.personalizado_13Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property personalizado_14() As String
            Get
                Return Me.personalizado_14Field
            End Get
            Set
                Me.personalizado_14Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property personalizado_15() As String
            Get
                Return Me.personalizado_15Field
            End Get
            Set
                Me.personalizado_15Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property personalizado_16() As String
            Get
                Return Me.personalizado_16Field
            End Get
            Set
                Me.personalizado_16Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property personalizado_17() As String
            Get
                Return Me.personalizado_17Field
            End Get
            Set
                Me.personalizado_17Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property personalizado_18() As String
            Get
                Return Me.personalizado_18Field
            End Get
            Set
                Me.personalizado_18Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property personalizado_19() As String
            Get
                Return Me.personalizado_19Field
            End Get
            Set
                Me.personalizado_19Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property personalizado_20() As String
            Get
                Return Me.personalizado_20Field
            End Get
            Set
                Me.personalizado_20Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property rangoFinalAutorizado() As String
            Get
                Return Me.rangoFinalAutorizadoField
            End Get
            Set
                Me.rangoFinalAutorizadoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property rangoInicialAutorizado() As String
            Get
                Return Me.rangoInicialAutorizadoField
            End Get
            Set
                Me.rangoInicialAutorizadoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property regimen2989() As Boolean
            Get
                Return Me.regimen2989Field
            End Get
            Set
                Me.regimen2989Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property regimenISR() As String
            Get
                Return Me.regimenISRField
            End Get
            Set
                Me.regimenISRField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property serieAutorizada() As String
            Get
                Return Me.serieAutorizadaField
            End Get
            Set
                Me.serieAutorizadaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property serieDocumento() As String
            Get
                Return Me.serieDocumentoField
            End Get
            Set
                Me.serieDocumentoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property telefonoComprador() As String
            Get
                Return Me.telefonoCompradorField
            End Get
            Set
                Me.telefonoCompradorField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property tipoCambio() As Double
            Get
                Return Me.tipoCambioField
            End Get
            Set
                Me.tipoCambioField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property tipoCambioSpecified() As Boolean
            Get
                Return Me.tipoCambioFieldSpecified
            End Get
            Set
                Me.tipoCambioFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property tipoDocumento() As String
            Get
                Return Me.tipoDocumentoField
            End Get
            Set
                Me.tipoDocumentoField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://listener.ingface.com/")>  _
    Partial Public Class detalleDte
        
        Private cantidadField As Double
        
        Private cantidadFieldSpecified As Boolean
        
        Private codigoProductoField As String
        
        Private descripcionProductoField As String
        
        Private detalleImpuestosIvaField As Double
        
        Private detalleImpuestosIvaFieldSpecified As Boolean
        
        Private importeExentoField As Double
        
        Private importeExentoFieldSpecified As Boolean
        
        Private importeNetoGravadoField As Double
        
        Private importeNetoGravadoFieldSpecified As Boolean
        
        Private importeOtrosImpuestosField As Double
        
        Private importeOtrosImpuestosFieldSpecified As Boolean
        
        Private importeTotalOperacionField As Double
        
        Private importeTotalOperacionFieldSpecified As Boolean
        
        Private montoBrutoField As Double
        
        Private montoBrutoFieldSpecified As Boolean
        
        Private montoDescuentoField As Double
        
        Private montoDescuentoFieldSpecified As Boolean
        
        Private personalizado_01Field As String
        
        Private personalizado_02Field As String
        
        Private personalizado_03Field As String
        
        Private personalizado_04Field As String
        
        Private personalizado_05Field As String
        
        Private personalizado_06Field As String
        
        Private precioUnitarioField As Double
        
        Private precioUnitarioFieldSpecified As Boolean
        
        Private tipoProductoField As String
        
        Private unidadMedidaField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property cantidad() As Double
            Get
                Return Me.cantidadField
            End Get
            Set
                Me.cantidadField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property cantidadSpecified() As Boolean
            Get
                Return Me.cantidadFieldSpecified
            End Get
            Set
                Me.cantidadFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property codigoProducto() As String
            Get
                Return Me.codigoProductoField
            End Get
            Set
                Me.codigoProductoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property descripcionProducto() As String
            Get
                Return Me.descripcionProductoField
            End Get
            Set
                Me.descripcionProductoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property detalleImpuestosIva() As Double
            Get
                Return Me.detalleImpuestosIvaField
            End Get
            Set
                Me.detalleImpuestosIvaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property detalleImpuestosIvaSpecified() As Boolean
            Get
                Return Me.detalleImpuestosIvaFieldSpecified
            End Get
            Set
                Me.detalleImpuestosIvaFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property importeExento() As Double
            Get
                Return Me.importeExentoField
            End Get
            Set
                Me.importeExentoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property importeExentoSpecified() As Boolean
            Get
                Return Me.importeExentoFieldSpecified
            End Get
            Set
                Me.importeExentoFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property importeNetoGravado() As Double
            Get
                Return Me.importeNetoGravadoField
            End Get
            Set
                Me.importeNetoGravadoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property importeNetoGravadoSpecified() As Boolean
            Get
                Return Me.importeNetoGravadoFieldSpecified
            End Get
            Set
                Me.importeNetoGravadoFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property importeOtrosImpuestos() As Double
            Get
                Return Me.importeOtrosImpuestosField
            End Get
            Set
                Me.importeOtrosImpuestosField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property importeOtrosImpuestosSpecified() As Boolean
            Get
                Return Me.importeOtrosImpuestosFieldSpecified
            End Get
            Set
                Me.importeOtrosImpuestosFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property importeTotalOperacion() As Double
            Get
                Return Me.importeTotalOperacionField
            End Get
            Set
                Me.importeTotalOperacionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property importeTotalOperacionSpecified() As Boolean
            Get
                Return Me.importeTotalOperacionFieldSpecified
            End Get
            Set
                Me.importeTotalOperacionFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property montoBruto() As Double
            Get
                Return Me.montoBrutoField
            End Get
            Set
                Me.montoBrutoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property montoBrutoSpecified() As Boolean
            Get
                Return Me.montoBrutoFieldSpecified
            End Get
            Set
                Me.montoBrutoFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property montoDescuento() As Double
            Get
                Return Me.montoDescuentoField
            End Get
            Set
                Me.montoDescuentoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property montoDescuentoSpecified() As Boolean
            Get
                Return Me.montoDescuentoFieldSpecified
            End Get
            Set
                Me.montoDescuentoFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property personalizado_01() As String
            Get
                Return Me.personalizado_01Field
            End Get
            Set
                Me.personalizado_01Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property personalizado_02() As String
            Get
                Return Me.personalizado_02Field
            End Get
            Set
                Me.personalizado_02Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property personalizado_03() As String
            Get
                Return Me.personalizado_03Field
            End Get
            Set
                Me.personalizado_03Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property personalizado_04() As String
            Get
                Return Me.personalizado_04Field
            End Get
            Set
                Me.personalizado_04Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property personalizado_05() As String
            Get
                Return Me.personalizado_05Field
            End Get
            Set
                Me.personalizado_05Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property personalizado_06() As String
            Get
                Return Me.personalizado_06Field
            End Get
            Set
                Me.personalizado_06Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property precioUnitario() As Double
            Get
                Return Me.precioUnitarioField
            End Get
            Set
                Me.precioUnitarioField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property precioUnitarioSpecified() As Boolean
            Get
                Return Me.precioUnitarioFieldSpecified
            End Get
            Set
                Me.precioUnitarioFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property tipoProducto() As String
            Get
                Return Me.tipoProductoField
            End Get
            Set
                Me.tipoProductoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property unidadMedida() As String
            Get
                Return Me.unidadMedidaField
            End Get
            Set
                Me.unidadMedidaField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://listener.ingface.com/")>  _
    Partial Public Class requestValidacion
        
        Private claveField As String
        
        Private codigoEstablecimientoField As String
        
        Private nitCompradorField As String
        
        Private nitVendedorField As String
        
        Private numeroDteField As String
        
        Private usuarioField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property clave() As String
            Get
                Return Me.claveField
            End Get
            Set
                Me.claveField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property codigoEstablecimiento() As String
            Get
                Return Me.codigoEstablecimientoField
            End Get
            Set
                Me.codigoEstablecimientoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property nitComprador() As String
            Get
                Return Me.nitCompradorField
            End Get
            Set
                Me.nitCompradorField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property nitVendedor() As String
            Get
                Return Me.nitVendedorField
            End Get
            Set
                Me.nitVendedorField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property numeroDte() As String
            Get
                Return Me.numeroDteField
            End Get
            Set
                Me.numeroDteField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property usuario() As String
            Get
                Return Me.usuarioField
            End Get
            Set
                Me.usuarioField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://listener.ingface.com/")>  _
    Partial Public Class requestAnulacionDte
        
        Private claveField As String
        
        Private codigoEstablecimientoField As String
        
        Private conceptoField As String
        
        Private fechaAnulacionField As Date
        
        Private fechaAnulacionFieldSpecified As Boolean
        
        Private numeroDteField As String
        
        Private tipoDocumentoField As String
        
        Private usuarioField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property clave() As String
            Get
                Return Me.claveField
            End Get
            Set
                Me.claveField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property codigoEstablecimiento() As String
            Get
                Return Me.codigoEstablecimientoField
            End Get
            Set
                Me.codigoEstablecimientoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property concepto() As String
            Get
                Return Me.conceptoField
            End Get
            Set
                Me.conceptoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property fechaAnulacion() As Date
            Get
                Return Me.fechaAnulacionField
            End Get
            Set
                Me.fechaAnulacionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property fechaAnulacionSpecified() As Boolean
            Get
                Return Me.fechaAnulacionFieldSpecified
            End Get
            Set
                Me.fechaAnulacionFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property numeroDte() As String
            Get
                Return Me.numeroDteField
            End Get
            Set
                Me.numeroDteField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property tipoDocumento() As String
            Get
                Return Me.tipoDocumentoField
            End Get
            Set
                Me.tipoDocumentoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property usuario() As String
            Get
                Return Me.usuarioField
            End Get
            Set
                Me.usuarioField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(responseDteSap)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(responseValidacion)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(responseAnulacionDte)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(responseDte)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(responseCierre)),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://listener.ingface.com/")>  _
    Partial Public Class resultado
        
        Private anotacionesField As String
        
        Private descripcionField As String
        
        Private validoField As Boolean
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property anotaciones() As String
            Get
                Return Me.anotacionesField
            End Get
            Set
                Me.anotacionesField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property descripcion() As String
            Get
                Return Me.descripcionField
            End Get
            Set
                Me.descripcionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property valido() As Boolean
            Get
                Return Me.validoField
            End Get
            Set
                Me.validoField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://listener.ingface.com/")>  _
    Partial Public Class responseDteSap
        Inherits resultado
        
        Private caeField As String
        
        Private estadoField As String
        
        Private numeroDocumentoField As String
        
        Private numeroDteField As String
        
        Private rangoFinalAutorizadoField As String
        
        Private rangoInicialAutorizadoField As String
        
        Private regimenField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property cae() As String
            Get
                Return Me.caeField
            End Get
            Set
                Me.caeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property estado() As String
            Get
                Return Me.estadoField
            End Get
            Set
                Me.estadoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property numeroDocumento() As String
            Get
                Return Me.numeroDocumentoField
            End Get
            Set
                Me.numeroDocumentoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property numeroDte() As String
            Get
                Return Me.numeroDteField
            End Get
            Set
                Me.numeroDteField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property rangoFinalAutorizado() As String
            Get
                Return Me.rangoFinalAutorizadoField
            End Get
            Set
                Me.rangoFinalAutorizadoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property rangoInicialAutorizado() As String
            Get
                Return Me.rangoInicialAutorizadoField
            End Get
            Set
                Me.rangoInicialAutorizadoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property regimen() As String
            Get
                Return Me.regimenField
            End Get
            Set
                Me.regimenField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://listener.ingface.com/")>  _
    Partial Public Class responseValidacion
        Inherits resultado
        
        Private dteField As dte
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property dte() As dte
            Get
                Return Me.dteField
            End Get
            Set
                Me.dteField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://listener.ingface.com/")>  _
    Partial Public Class responseAnulacionDte
        Inherits resultado
        
        Private dteField As dte
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property dte() As dte
            Get
                Return Me.dteField
            End Get
            Set
                Me.dteField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://listener.ingface.com/")>  _
    Partial Public Class responseDte
        Inherits resultado
        
        Private caeField As String
        
        Private estadoField As String
        
        Private numeroDocumentoField As Long
        
        Private numeroDteField As String
        
        Private rangoFinalAutorizadoField As String
        
        Private rangoInicialAutorizadoField As String
        
        Private regimenField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property cae() As String
            Get
                Return Me.caeField
            End Get
            Set
                Me.caeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property estado() As String
            Get
                Return Me.estadoField
            End Get
            Set
                Me.estadoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property numeroDocumento() As Long
            Get
                Return Me.numeroDocumentoField
            End Get
            Set
                Me.numeroDocumentoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property numeroDte() As String
            Get
                Return Me.numeroDteField
            End Get
            Set
                Me.numeroDteField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property rangoFinalAutorizado() As String
            Get
                Return Me.rangoFinalAutorizadoField
            End Get
            Set
                Me.rangoFinalAutorizadoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property rangoInicialAutorizado() As String
            Get
                Return Me.rangoInicialAutorizadoField
            End Get
            Set
                Me.rangoInicialAutorizadoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property regimen() As String
            Get
                Return Me.regimenField
            End Get
            Set
                Me.regimenField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://listener.ingface.com/")>  _
    Partial Public Class responseCierre
        Inherits resultado
        
        Private checkSumField As String
        
        Private codigoCaeField As String
        
        Private codigoCrfmField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property checkSum() As String
            Get
                Return Me.checkSumField
            End Get
            Set
                Me.checkSumField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property codigoCae() As String
            Get
                Return Me.codigoCaeField
            End Get
            Set
                Me.codigoCaeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property codigoCrfm() As String
            Get
                Return Me.codigoCrfmField
            End Get
            Set
                Me.codigoCrfmField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")>  _
    Public Delegate Sub helloCompletedEventHandler(ByVal sender As Object, ByVal e As helloCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class helloCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")>  _
    Public Delegate Sub registrarDteCompletedEventHandler(ByVal sender As Object, ByVal e As registrarDteCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class registrarDteCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As responseDte
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),responseDte)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")>  _
    Public Delegate Sub anulacionDteCompletedEventHandler(ByVal sender As Object, ByVal e As anulacionDteCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class anulacionDteCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As responseAnulacionDte
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),responseAnulacionDte)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")>  _
    Public Delegate Sub cierreCompletedEventHandler(ByVal sender As Object, ByVal e As cierreCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class cierreCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As responseCierre
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),responseCierre)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")>  _
    Public Delegate Sub validacionDteCompletedEventHandler(ByVal sender As Object, ByVal e As validacionDteCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class validacionDteCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As responseValidacion
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),responseValidacion)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")>  _
    Public Delegate Sub cargarDteCompletedEventHandler(ByVal sender As Object, ByVal e As cargarDteCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class cargarDteCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As responseDte
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),responseDte)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")>  _
    Public Delegate Sub registrarDteSapCompletedEventHandler(ByVal sender As Object, ByVal e As registrarDteSapCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class registrarDteSapCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As responseDteSap
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),responseDteSap)
            End Get
        End Property
    End Class
End Namespace
