'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34014
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Data
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.34014.
'
Namespace WSFace
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="FactWSFrontSoap", [Namespace]:="http://www.fact.com.mx/schema/ws")>  _
    Partial Public Class FactWSFront
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private RequestTransactionOperationCompleted As System.Threading.SendOrPostCallback
        
        Private SSLTransactionOperationCompleted As System.Threading.SendOrPostCallback
        
        Private SecureTransactionOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.FACE.My.MySettings.Default.FACE_WSFace_FactWSFront
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event RequestTransactionCompleted As RequestTransactionCompletedEventHandler
        
        '''<remarks/>
        Public Event SSLTransactionCompleted As SSLTransactionCompletedEventHandler
        
        '''<remarks/>
        Public Event SecureTransactionCompleted As SecureTransactionCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.fact.com.mx/schema/ws/RequestTransaction", RequestNamespace:="http://www.fact.com.mx/schema/ws", ResponseNamespace:="http://www.fact.com.mx/schema/ws", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function RequestTransaction(ByVal Requestor As String, ByVal Transaction As String, ByVal Country As String, ByVal Entity As String, ByVal User As String, ByVal UserName As String, ByVal Data1 As String, ByVal Data2 As String, ByVal Data3 As String) As TransactionTag
            Dim results() As Object = Me.Invoke("RequestTransaction", New Object() {Requestor, Transaction, Country, Entity, User, UserName, Data1, Data2, Data3})
            Return CType(results(0),TransactionTag)
        End Function
        
        '''<remarks/>
        Public Overloads Sub RequestTransactionAsync(ByVal Requestor As String, ByVal Transaction As String, ByVal Country As String, ByVal Entity As String, ByVal User As String, ByVal UserName As String, ByVal Data1 As String, ByVal Data2 As String, ByVal Data3 As String)
            Me.RequestTransactionAsync(Requestor, Transaction, Country, Entity, User, UserName, Data1, Data2, Data3, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub RequestTransactionAsync(ByVal Requestor As String, ByVal Transaction As String, ByVal Country As String, ByVal Entity As String, ByVal User As String, ByVal UserName As String, ByVal Data1 As String, ByVal Data2 As String, ByVal Data3 As String, ByVal userState As Object)
            If (Me.RequestTransactionOperationCompleted Is Nothing) Then
                Me.RequestTransactionOperationCompleted = AddressOf Me.OnRequestTransactionOperationCompleted
            End If
            Me.InvokeAsync("RequestTransaction", New Object() {Requestor, Transaction, Country, Entity, User, UserName, Data1, Data2, Data3}, Me.RequestTransactionOperationCompleted, userState)
        End Sub
        
        Private Sub OnRequestTransactionOperationCompleted(ByVal arg As Object)
            If (Not (Me.RequestTransactionCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent RequestTransactionCompleted(Me, New RequestTransactionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.fact.com.mx/schema/ws/SSLTransaction", RequestNamespace:="http://www.fact.com.mx/schema/ws", ResponseNamespace:="http://www.fact.com.mx/schema/ws", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SSLTransaction(ByVal Entity As String, ByVal DataExchange As String) As String
            Dim results() As Object = Me.Invoke("SSLTransaction", New Object() {Entity, DataExchange})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub SSLTransactionAsync(ByVal Entity As String, ByVal DataExchange As String)
            Me.SSLTransactionAsync(Entity, DataExchange, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SSLTransactionAsync(ByVal Entity As String, ByVal DataExchange As String, ByVal userState As Object)
            If (Me.SSLTransactionOperationCompleted Is Nothing) Then
                Me.SSLTransactionOperationCompleted = AddressOf Me.OnSSLTransactionOperationCompleted
            End If
            Me.InvokeAsync("SSLTransaction", New Object() {Entity, DataExchange}, Me.SSLTransactionOperationCompleted, userState)
        End Sub
        
        Private Sub OnSSLTransactionOperationCompleted(ByVal arg As Object)
            If (Not (Me.SSLTransactionCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent SSLTransactionCompleted(Me, New SSLTransactionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.fact.com.mx/schema/ws/SecureTransaction", RequestNamespace:="http://www.fact.com.mx/schema/ws", ResponseNamespace:="http://www.fact.com.mx/schema/ws", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SecureTransaction(ByVal Entity As String, ByVal DataExchange As String) As String
            Dim results() As Object = Me.Invoke("SecureTransaction", New Object() {Entity, DataExchange})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub SecureTransactionAsync(ByVal Entity As String, ByVal DataExchange As String)
            Me.SecureTransactionAsync(Entity, DataExchange, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SecureTransactionAsync(ByVal Entity As String, ByVal DataExchange As String, ByVal userState As Object)
            If (Me.SecureTransactionOperationCompleted Is Nothing) Then
                Me.SecureTransactionOperationCompleted = AddressOf Me.OnSecureTransactionOperationCompleted
            End If
            Me.InvokeAsync("SecureTransaction", New Object() {Entity, DataExchange}, Me.SecureTransactionOperationCompleted, userState)
        End Sub
        
        Private Sub OnSecureTransactionOperationCompleted(ByVal arg As Object)
            If (Not (Me.SecureTransactionCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent SecureTransactionCompleted(Me, New SecureTransactionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fact.com.mx/schema/ws")>  _
    Partial Public Class TransactionTag
        
        Private requestField As FactRequest
        
        Private responseField As FactResponse
        
        Private responseDataField As FactResponseData
        
        '''<remarks/>
        Public Property Request() As FactRequest
            Get
                Return Me.requestField
            End Get
            Set
                Me.requestField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Response() As FactResponse
            Get
                Return Me.responseField
            End Get
            Set
                Me.responseField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ResponseData() As FactResponseData
            Get
                Return Me.responseDataField
            End Get
            Set
                Me.responseDataField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fact.com.mx/schema/ws")>  _
    Partial Public Class FactRequest
        
        Private requestorField As System.Guid
        
        Private requestorNameField As String
        
        Private requestorActiveField As Boolean
        
        Private transactionField As Transactions
        
        Private countryField As String
        
        Private entityField As String
        
        Private userField As System.Guid
        
        Private userNameField As String
        
        Private idField As System.Guid
        
        Private timeStampField As Date
        
        '''<remarks/>
        Public Property Requestor() As System.Guid
            Get
                Return Me.requestorField
            End Get
            Set
                Me.requestorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RequestorName() As String
            Get
                Return Me.requestorNameField
            End Get
            Set
                Me.requestorNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RequestorActive() As Boolean
            Get
                Return Me.requestorActiveField
            End Get
            Set
                Me.requestorActiveField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Transaction() As Transactions
            Get
                Return Me.transactionField
            End Get
            Set
                Me.transactionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Country() As String
            Get
                Return Me.countryField
            End Get
            Set
                Me.countryField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Entity() As String
            Get
                Return Me.entityField
            End Get
            Set
                Me.entityField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property User() As System.Guid
            Get
                Return Me.userField
            End Get
            Set
                Me.userField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UserName() As String
            Get
                Return Me.userNameField
            End Get
            Set
                Me.userNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Id() As System.Guid
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TimeStamp() As Date
            Get
                Return Me.timeStampField
            End Get
            Set
                Me.timeStampField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fact.com.mx/schema/ws")>  _
    Public Enum Transactions
        
        '''<remarks/>
        BASE
        
        '''<remarks/>
        NO_TRANSACTION
        
        '''<remarks/>
        CONVERT_NATIVE_XML
        
        '''<remarks/>
        GET_MTE_BATCH
        
        '''<remarks/>
        PROCESS_BATCH
        
        '''<remarks/>
        SYSTEM_REQUEST
        
        '''<remarks/>
        RECEIVE_BATCH
        
        '''<remarks/>
        ENROLL_CERT
        
        '''<remarks/>
        GET_XML
        
        '''<remarks/>
        GET_HTML
        
        '''<remarks/>
        GET_XML_AND_HTML
        
        '''<remarks/>
        CANCEL_XML
        
        '''<remarks/>
        MARK_XML_AS_PAID
        
        '''<remarks/>
        MARK_XML_AS_UNPAID
        
        '''<remarks/>
        SEARCH_BASIC
        
        '''<remarks/>
        GET_MONTHLY_REPORT
        
        '''<remarks/>
        GET_MONTHLY_REPORT_FOR_PROVIDER
        
        '''<remarks/>
        GET_FOLIOS_BY_RFC
        
        '''<remarks/>
        DOES_ASSIGNMENT_EXIST
        
        '''<remarks/>
        CANCEL_XML_BY_INTERNAL_ID
        
        '''<remarks/>
        ACTIVATE_ASSIGNMENT
        
        '''<remarks/>
        COUNT_ACTIVE_ASSIGNMENTS
        
        '''<remarks/>
        GET_DOCUMENT
        
        '''<remarks/>
        AUTHENTICATE_USER
        
        '''<remarks/>
        GET_ACCOUNT
        
        '''<remarks/>
        DISTRIBUTE
        
        '''<remarks/>
        QUEUE_FOR_DISTRIBUTION
        
        '''<remarks/>
        GET_EFFECTIVE_RIGHTS
        
        '''<remarks/>
        EXEC_STORED_PROC
        
        '''<remarks/>
        GET_USER_INFO
        
        '''<remarks/>
        RECEIVE
        
        '''<remarks/>
        GET_PREVIEW
        
        '''<remarks/>
        RETRIEVE_DOCUMENT
        
        '''<remarks/>
        MARK_DOCUMENT_AS_PAID
        
        '''<remarks/>
        MARK_DOCUMENT_AS_NOT_PAID
        
        '''<remarks/>
        CANCEL_DOCUMENT
        
        '''<remarks/>
        MARK_DOCUMENT_AS_DELETED
        
        '''<remarks/>
        MARK_DOCUMENT_AS_NOT_DELETED
        
        '''<remarks/>
        GET_ADDENDA_RECEIVERS
        
        '''<remarks/>
        REQUEST_PASSWORD_CHANGE
        
        '''<remarks/>
        CHANGE_DOCUMENT_SUCURSAL
        
        '''<remarks/>
        CREATE_ACCOUNT_AS_OWNER
        
        '''<remarks/>
        CREATE_PASSWORD
        
        '''<remarks/>
        PASSWORD_FORGOT
        
        '''<remarks/>
        CREATE_USER
        
        '''<remarks/>
        INCREMENT_BUNDLE_SIZE
        
        '''<remarks/>
        TIMBRAR
        
        '''<remarks/>
        LOOKUP_ISSUED_INTERNAL_ID
        
        '''<remarks/>
        VALIDATE_CERT
        
        '''<remarks/>
        BATCH_SERIAL_OPERATIONS
        
        '''<remarks/>
        PROCESS_LCO
        
        '''<remarks/>
        ENROLL_THIRD_PARTY_CERT
        
        '''<remarks/>
        CANCEL_CFDI
        
        '''<remarks/>
        UPDATE_ACCOUNT_DATA
        
        '''<remarks/>
        ASSIGN_ACCOUNT_REQUESTOR
        
        '''<remarks/>
        UPDATE_USER_DATA
        
        '''<remarks/>
        UPDATE_ADMIN_USER_DATA
        
        '''<remarks/>
        CREATE_ADMIN_USER
        
        '''<remarks/>
        UPSERT_GRAPHIC_REPRESENTATION
        
        '''<remarks/>
        LOOKUP_ISSUED_BATCH_AND_SERIAL
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fact.com.mx/schema/ws")>  _
    Partial Public Class FactResponseData
        
        Private responseData1Field As String
        
        Private responseData2Field As String
        
        Private responseData3Field As String
        
        Private responseDataSetField As System.Data.DataSet
        
        '''<remarks/>
        Public Property ResponseData1() As String
            Get
                Return Me.responseData1Field
            End Get
            Set
                Me.responseData1Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ResponseData2() As String
            Get
                Return Me.responseData2Field
            End Get
            Set
                Me.responseData2Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ResponseData3() As String
            Get
                Return Me.responseData3Field
            End Get
            Set
                Me.responseData3Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ResponseDataSet() As System.Data.DataSet
            Get
                Return Me.responseDataSetField
            End Get
            Set
                Me.responseDataSetField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fact.com.mx/schema/ws")>  _
    Partial Public Class BatchID
        
        Private batchIdField As String
        
        Private batchTimeStampField As String
        
        Private batchRequestorCountryField As String
        
        Private batchRequestorEntityField As String
        
        Private batchPositionField As String
        
        '''<remarks/>
        Public Property BatchId() As String
            Get
                Return Me.batchIdField
            End Get
            Set
                Me.batchIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BatchTimeStamp() As String
            Get
                Return Me.batchTimeStampField
            End Get
            Set
                Me.batchTimeStampField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BatchRequestorCountry() As String
            Get
                Return Me.batchRequestorCountryField
            End Get
            Set
                Me.batchRequestorCountryField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BatchRequestorEntity() As String
            Get
                Return Me.batchRequestorEntityField
            End Get
            Set
                Me.batchRequestorEntityField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BatchPosition() As String
            Get
                Return Me.batchPositionField
            End Get
            Set
                Me.batchPositionField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fact.com.mx/schema/ws")>  _
    Partial Public Class DocID
        
        Private countryField As String
        
        Private entityField As String
        
        Private fiscalNameField As String
        
        Private aYearField As String
        
        Private aNumberField As String
        
        Private batchField As String
        
        Private serialField As String
        
        Private documentGUIDField As String
        
        Private issuedTimeStampField As String
        
        Private enrolledTimeStampField As String
        
        Private paidTimeStampField As String
        
        Private cancelledTimeStampField As String
        
        Private internalIDField As String
        
        Private batchIDField As String
        
        Private batchTimeStampField As String
        
        Private batchRequestorCountryField As String
        
        Private batchRequestorEntityField As String
        
        Private batchPositionField As String
        
        Private receiverCountryField As String
        
        Private receiverEntityField As String
        
        Private receiverTaxIDField As String
        
        Private receiverNameField As String
        
        Private claveAgenteField As String
        
        Private numeroDePolizaField As String
        
        Private currencyField As String
        
        Private totalAmountField As String
        
        Private type1Field As String
        
        Private type2Field As String
        
        Private suggestedFileNameField As String
        
        Private suggestedFileName2Field As String
        
        '''<remarks/>
        Public Property Country() As String
            Get
                Return Me.countryField
            End Get
            Set
                Me.countryField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Entity() As String
            Get
                Return Me.entityField
            End Get
            Set
                Me.entityField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FiscalName() As String
            Get
                Return Me.fiscalNameField
            End Get
            Set
                Me.fiscalNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property AYear() As String
            Get
                Return Me.aYearField
            End Get
            Set
                Me.aYearField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ANumber() As String
            Get
                Return Me.aNumberField
            End Get
            Set
                Me.aNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Batch() As String
            Get
                Return Me.batchField
            End Get
            Set
                Me.batchField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Serial() As String
            Get
                Return Me.serialField
            End Get
            Set
                Me.serialField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DocumentGUID() As String
            Get
                Return Me.documentGUIDField
            End Get
            Set
                Me.documentGUIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IssuedTimeStamp() As String
            Get
                Return Me.issuedTimeStampField
            End Get
            Set
                Me.issuedTimeStampField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property EnrolledTimeStamp() As String
            Get
                Return Me.enrolledTimeStampField
            End Get
            Set
                Me.enrolledTimeStampField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PaidTimeStamp() As String
            Get
                Return Me.paidTimeStampField
            End Get
            Set
                Me.paidTimeStampField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CancelledTimeStamp() As String
            Get
                Return Me.cancelledTimeStampField
            End Get
            Set
                Me.cancelledTimeStampField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property InternalID() As String
            Get
                Return Me.internalIDField
            End Get
            Set
                Me.internalIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BatchID() As String
            Get
                Return Me.batchIDField
            End Get
            Set
                Me.batchIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BatchTimeStamp() As String
            Get
                Return Me.batchTimeStampField
            End Get
            Set
                Me.batchTimeStampField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BatchRequestorCountry() As String
            Get
                Return Me.batchRequestorCountryField
            End Get
            Set
                Me.batchRequestorCountryField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BatchRequestorEntity() As String
            Get
                Return Me.batchRequestorEntityField
            End Get
            Set
                Me.batchRequestorEntityField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BatchPosition() As String
            Get
                Return Me.batchPositionField
            End Get
            Set
                Me.batchPositionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ReceiverCountry() As String
            Get
                Return Me.receiverCountryField
            End Get
            Set
                Me.receiverCountryField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ReceiverEntity() As String
            Get
                Return Me.receiverEntityField
            End Get
            Set
                Me.receiverEntityField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ReceiverTaxID() As String
            Get
                Return Me.receiverTaxIDField
            End Get
            Set
                Me.receiverTaxIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ReceiverName() As String
            Get
                Return Me.receiverNameField
            End Get
            Set
                Me.receiverNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ClaveAgente() As String
            Get
                Return Me.claveAgenteField
            End Get
            Set
                Me.claveAgenteField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NumeroDePoliza() As String
            Get
                Return Me.numeroDePolizaField
            End Get
            Set
                Me.numeroDePolizaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Currency() As String
            Get
                Return Me.currencyField
            End Get
            Set
                Me.currencyField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TotalAmount() As String
            Get
                Return Me.totalAmountField
            End Get
            Set
                Me.totalAmountField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Type1() As String
            Get
                Return Me.type1Field
            End Get
            Set
                Me.type1Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Type2() As String
            Get
                Return Me.type2Field
            End Get
            Set
                Me.type2Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SuggestedFileName() As String
            Get
                Return Me.suggestedFileNameField
            End Get
            Set
                Me.suggestedFileNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SuggestedFileName2() As String
            Get
                Return Me.suggestedFileName2Field
            End Get
            Set
                Me.suggestedFileName2Field = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fact.com.mx/schema/ws")>  _
    Partial Public Class FactResponse
        
        Private resultField As Boolean
        
        Private timeStampField As Date
        
        Private lastResultField As String
        
        Private codeField As Integer
        
        Private descriptionField As String
        
        Private hintField As String
        
        Private dataField As String
        
        Private processorField As String
        
        Private identifierField As DocID
        
        Private batchIdentifierField As BatchID
        
        '''<remarks/>
        Public Property Result() As Boolean
            Get
                Return Me.resultField
            End Get
            Set
                Me.resultField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TimeStamp() As Date
            Get
                Return Me.timeStampField
            End Get
            Set
                Me.timeStampField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LastResult() As String
            Get
                Return Me.lastResultField
            End Get
            Set
                Me.lastResultField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Code() As Integer
            Get
                Return Me.codeField
            End Get
            Set
                Me.codeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Description() As String
            Get
                Return Me.descriptionField
            End Get
            Set
                Me.descriptionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Hint() As String
            Get
                Return Me.hintField
            End Get
            Set
                Me.hintField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Data() As String
            Get
                Return Me.dataField
            End Get
            Set
                Me.dataField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Processor() As String
            Get
                Return Me.processorField
            End Get
            Set
                Me.processorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Identifier() As DocID
            Get
                Return Me.identifierField
            End Get
            Set
                Me.identifierField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BatchIdentifier() As BatchID
            Get
                Return Me.batchIdentifierField
            End Get
            Set
                Me.batchIdentifierField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")>  _
    Public Delegate Sub RequestTransactionCompletedEventHandler(ByVal sender As Object, ByVal e As RequestTransactionCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class RequestTransactionCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As TransactionTag
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),TransactionTag)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")>  _
    Public Delegate Sub SSLTransactionCompletedEventHandler(ByVal sender As Object, ByVal e As SSLTransactionCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class SSLTransactionCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")>  _
    Public Delegate Sub SecureTransactionCompletedEventHandler(ByVal sender As Object, ByVal e As SecureTransactionCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class SecureTransactionCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
End Namespace
