CREATE PROCEDURE [dbo].[SP_IT_DATOS_DETALLE] (@DOCENTRY VARCHAR(10),@TIPODOC CHAR(4))
AS

DECLARE @DOCRATE AS NUMERIC(19,6)
DECLARE @MONEDA AS VARCHAR(3)

IF @TIPODOC ='FAC' OR @TIPODOC='ND'
	SELECT @MONEDA=DOCCUR,@DOCRATE=DOCRATE
	FROM OINV 
	WHERE DOCENTRY=@DOCENTRY
ELSE
	SELECT @MONEDA=DOCCUR,@DOCRATE=DOCRATE
	FROM ORIN 
	WHERE DOCENTRY=@DOCENTRY
	
IF @MONEDA <> 'USD'
	SET @DOCRATE=1
	
IF @TIPODOC ='FAC' OR @TIPODOC='ND'
	SELECT 
		ISNULL(A.Quantity,0) CANTIDAD,
		ISNULL(A.ItemCode,'N/A') CODIGO_PRODUCTO,
		ISNULL(A.dscription,'N/A') DESCRIPCION_PRODUCTO,
		ISNULL(A.gtotal,0) MONTO_BRUTO,
		ISNULL(A.Price,0)  * @DOCRATE PRECIO_UNITARIO,
		A.TaxCode TIPO_IMPUESTO,
		CASE A.TAXCODE WHEN 'EXE' THEN A.GTotal  ELSE 0 END IMPORTE_EXENTO,
		ISNULL(A.GTotal,0)  IMPORTE_NETO_GRAVADO,
		ISNULL(A.GTOTAL,0)  TOTAL_OPERACION,
		0.00000 MONTO_DESCUENTO,
		--ISNULL(C.SalUnitMsr,'N/D') UNIDAD_MEDIDA,
		'UND' UNIDAD_MEDIDA,
		ISNULL(A.VatSum,0) IMPUESTO,
		B.DocType TIPO_DOC,
		0.0000 IMPORTE_OTROS_IMPUESTOS,
		0.0000 TOTAL_DESCUENTO_LINEA
	FROM INV1 A
	INNER JOIN OINV B
	ON A.DocEntry  = B.DocEntry 
	INNER JOIN OITM C
	ON A.ItemCode =C.ItemCode 
	WHERE A.DocEntry = @DOCENTRY
ELSE
	SELECT 
		ISNULL(A.Quantity,0) CANTIDAD,
		ISNULL(A.ItemCode,'N/A') CODIGO_PRODUCTO,
		ISNULL(A.dscription,'N/A') DESCRIPCION_PRODUCTO,
		ISNULL(A.gtotal,0) MONTO_BRUTO,
		ISNULL(A.Price,0)  * @DOCRATE PRECIO_UNITARIO,
		A.TaxCode TIPO_IMPUESTO,
		CASE A.TAXCODE WHEN 'EXE' THEN A.GTotal  ELSE 0 END IMPORTE_EXENTO,
		ISNULL(A.GTotal,0)  IMPORTE_NETO_GRAVADO,
		ISNULL(A.GTOTAL,0)  TOTAL_OPERACION,
		0.00000 MONTO_DESCUENTO,
		--ISNULL(C.SalUnitMsr,'N/D') UNIDAD_MEDIDA,
		'UND' UNIDAD_MEDIDA,
		ISNULL(A.VatSum,0) IMPUESTO,
		B.DocType TIPO_DOC,
		0.0000 IMPORTE_OTROS_IMPUESTOS,
		0.0000 TOTAL_DESCUENTO_LINEA
	FROM RIN1 A
	INNER JOIN OINV B
	ON A.DocEntry  = B.DocEntry 
	INNER JOIN OITM C
	ON A.ItemCode =C.ItemCode 
	WHERE A.DocEntry = @DOCENTRY