CREATE FUNCTION [dbo].[TIPODOC_GFACE](@CODE INT) RETURNS varchar(20) 
AS 
BEGin

	DECLARE @RESULT varchar(20)
	
	select @RESULT=Code 
	from [@FACE_TIPODOC]
	WHERE U_CODIGO = @CODE

	RETURN @RESULT
END